### ISSUE TITLE
drop the navlogin on the desktop

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#191]
@abrasax has requested that we drop the extra white banner on the texts page on the desktop and use the same banner as we have on mobile right now on the desktop as well.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
I can see the white banner gone in the Reader section. the Alpheios logo is also gone. in the mobile we have Alpheios logo and main menu, in desktop it's main menu and Reader. shall we add the Alpheios logo?

**Comment by balmas** [comment]
yes we want the desktop banner to be the same as the mobile -- i.e. dropping the Reader, Collection, etc. and just having the logo.

**Comment by irina060981** [comment]
I am a little confused here.
we have 3 variants of header now (before changes) - using Collections as example:

Desktop
![image](https://user-images.githubusercontent.com/12377640/60012115-86bd0d00-96be-11e9-9b96-acd549a2278d.png)

Tablet
![image](https://user-images.githubusercontent.com/12377640/60012131-92103880-96be-11e9-8ce7-c1079a90da8d.png)

Mobile
![image](https://user-images.githubusercontent.com/12377640/60012176-a2281800-96be-11e9-9f66-e93179c941ae.png)


So I have removed white banner on texts page - so  it becomes as on a tablet
![image](https://user-images.githubusercontent.com/12377640/60012214-bd932300-96be-11e9-971b-c52ada543ea6.png)

So am I right I should do he following:
 - remove in all layouts navbar-texts (Reader, Collection)
 - place logo instead of title
?

**Comment by monzug** [comment]
I think it's only for the text pages.

**Comment by balmas** [comment]
No, we're changing the banner on all the pages, to just the logo for now, so that desktop is identical to mobile.

**Comment by monzug** [comment]
ok. it did say text pages on the issue so I thought only the reader. How about the log in?

**Comment by irina060981** [comment]
For readers page - I placed login/logout to left menu (similiar as mobile)
is it ok?

**Comment by monzug** [comment]
I think that's the way to go.

**Comment by balmas** [comment]
agree

**Comment by irina060981** [comment]
Would look like this
![image](https://user-images.githubusercontent.com/12377640/60096064-657a2080-9793-11e9-9da6-b0d72315c3c2.png)

**Comment by monzug** [comment]
and log in info will go back in the Main Menu, correct?

**Comment by irina060981** [comment]
yes it would be there
![image](https://user-images.githubusercontent.com/12377640/60098834-bee54e00-9799-11e9-92dc-9e264eff80fe.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by monzug** [comment]
looks good. one last question. as we want the desktop and mobile to look alike, on desktop we have the logo + Reader center just above the Main Menu. is it ok that we do not show it on mobile?

**Comment by balmas** [comment]
hmm. I hate to get rid of it because I liked that design element, but liked the white navbar too... I guess we should remove it for consistency.

**Comment by irina060981** [comment]
then I think 
it woul look like this

![image](https://user-images.githubusercontent.com/12377640/60593038-414abf00-9de5-11e9-9898-16b566335d9d.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
up at texts-test

**Comment by monzug** [comment]
sorry to see it gone. verified.
