### ISSUE TITLE
Apology, Plato - add break for section identifier 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#219]
in https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0059.tlg002.perseus-grc2/passage/17-21, the first paragrapher identifier 17a has space break from the text, all the other  paragrapher  identifier don't have any space in the text. I believe we are also missing the section identifier such as 17, 18 etc.
in Scaife, section  and paragrapher identifier have space breaks.
see screenshot
![space-break](https://user-images.githubusercontent.com/41396793/61310193-cf4d7f00-a7c1-11e9-95ba-52cab980ca27.JPG)

**Comment by balmas** [comment]
I think when @abrasax and I looked at this before, we decided not to break out the section milestones into new lines.  17a shows up on a new line because it's outside of the paragraph div. I can move it to inside the div to address that (and look for and fix others) so it's at least consistent throughout our display.

**Comment by balmas** [comment]
the 17a section should now appear inline with the rest. I couldn't find other instances of this problem in this text.

**Comment by balmas** [comment]
ok NOW it's there :-)

**Comment by monzug** [comment]
yes.
