### ISSUE TITLE
Cicero, Academica: the notes in liber secundus and tertius are part of the text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#233]
Scrolling through Academica, Cicero, liber secundus and tertius looked funny. comparing with Perseus, I realized that we do not display the notes as such but they are part of the text.
see screenshots
in perseus
![academica-notes-perseus](https://user-images.githubusercontent.com/41396793/61812415-7315db00-ae11-11e9-9914-1c6c84178f8c.JPG)
in alpheios
![notes-cicero-alpheios](https://user-images.githubusercontent.com/41396793/61812416-73ae7180-ae11-11e9-868e-01a355c29cf3.JPG)

**Comment by balmas** [comment]
another strange thing -- books 2 and 3 aren't in the toc

**Comment by balmas** [comment]
I'm not sure what to do about this text.

1. Books 2 and 3 don't appear in the TOC because they don't follow the citation scheme of book/section -- they don't have any sections.

2. The notes appear inline because they are notes on blockquotes, which are often used for attributing sources. 

I'm tempted to just exclude books 2 and 3 for now. What do you think @monzug and @abrasax ?

**Comment by balmas** [comment]
per discussion with @abrasax we will remove books 2 and 3 and make a note in the bibliographic metadata.

**Comment by monzug** [comment]
book 2 and 3 and gone, the biblio note is the following:
Academica, Academicorum reliquiae cum Lucullo. (Book 1. Books 2 and 3 are currently pending editing of the digital edition.) Cicero, Marcus Tullius, creator; Plasberg, Otto, 1869-1924, edito
