### ISSUE TITLE
Tertulliam has two entries in Latin text collections

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#31]
in Scaife we have one entry with tertulliam  urn:cts:latinLit:stoa0276/      and 4 books: 
Ad Uxorem
Adversus Omnes Haereses
Carmen De Iona et Ninive
Incerti Auctoris Carmen Sodoma

then an other entry for Tertullian ca. 160-ca. 230
urn:cts:latinLit:stoa0275/  with 30 books.

in Perseus, again two entries, each with one book only: Tertullian, De Spectaculis
T.R. Glover, Ed. 
the other Tertullian, Apologeticum
T.R. Glover, Ed.
in perseus catalog, 39 books

in Alpheios, we have two entries, one with only one book: ad uxorem.

two issues here:
1) we are missing more content for the Pseudo-Tertullian
 (7 books missing vs Perseus:
Incerti Auctoris Carmen Sodoma,
Adversus Omnes Haereses
Genesis
De execrandis gentis diis
De Iudicio Domini
Carmen adversus Marcionitas
Carmen De Iona et Ninive)

(3 books missing versus Scaife:
Adversus Omnes Haereses
Carmen De Iona et Ninive
Incerti Auctoris Carmen Sodoma)

2) shall we regroup all the books under Tertullian? maybe by adding pseudo-Tertullian for the above books like in Perseus

**Comment by monzug** [comment]
in the perseus catalog, there is only one entry for Tertullian with 39 books: http://catalog.perseus.org/?_=1551285068590&f%5Btg_facet%5D%5B%5D=Tertullian+ca.+160-ca.+230&page=2&q=tg_no_token%3A%5BT+TO+U%5D

**Comment by monzug** [comment]
an other issue is the top navigation. Unfortunately there is no way for me to check the source for the navigation. clicking on source I can see that there are more info than in the xml file, looks like they come from Scaife that has two editions of this book.
here is an example of wrong navigation in Alpheios for De Spetaculis book :
Text Collections
Classical Latin
Tertullian ca. 160-ca. 230
De Spectaculis
**De Spectaculis, Tertullian, Apology, De spectaculis**  this is not necessary and not correct as Apology is a book on its own (and it's also in English) - this info comes from Scaifeit looks like we have the edition from Scaife in the top navigation

**Comment by monzug** [comment]
I did not close it or not intentionally... weird.

**Comment by balmas** [comment]
Re navigation data: The navigation data comes from a separate metadata file.
In the latest build, I'm experimenting with dropping the edition details from the breadcrumb navigation and just replacing it with "Text". Although I just realized, the browse display now also shows "Text" when it should maybe say "Browse".  What do you think about this? I wonder if I should use "Read" instead of "Text" for the text display.  I am thinking it would be good to add the passage info to the breadcrumb too.

**Comment by balmas** [comment]
as for the Tertullian texts, I think probably the author metadata for the works for stoa0276 should say Pseudo-Tertullian instead of Tertullian.  We are only including a subset of the texts included in Scaife right now. We may narrow them down even further before release, not sure yet.  I'll submit a PR for the name change on stoa0276

**Comment by monzug** [comment]
Ok, I thought I had to compare also the books # vs Perseus/Scaife. Happy if we use Pseudo-Tertullian so it's less confusing. as per text vs browse vs read, definitely text for both browse and read is not a good idea. I am more inclined to see browse and read.

**Comment by monzug** [comment]
looking more closely, we have text collections, then in the search field it says Find a text. at this point maybe we should replace read with text.  we inherited Read from Scaife, not sure if we have any ties with that project.

**Comment by balmas** [comment]
Submitted request for change to Pseudo-Tertullian as a PR. Won't be in a core corpus but submitted fix anyway.  Other issues for interface will be handled through the other issues.

**Comment by balmas** [comment]
PR was merged.
