### ISSUE TITLE
Suggestion: can we group the 44 books of Cicero by category? 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#44]
looking at the Latin Library, http://www.thelatinlibrary.com/cic.html, the books are split in 3 categories:
ORATORIA  PHILOSOPHIA  EPISTULAE
I really don't mind this as it put some order in the books rather than just alphabetically.
what do you think?

**Comment by balmas** [comment]
would like thoughts from @abrasax on this

**Comment by monzug** [comment]
Absolutely, please!

**Comment by abrasax** [comment]
I think so                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bridget AlmasSent: Friday, March 8, 2019 8:02 AMTo: alpheios-project/alpheios_nemo_uiReply To: alpheios-project/alpheios_nemo_uiCc: Harry Diakoff; MentionSubject: Re: [alpheios-project/alpheios_nemo_ui] Suggestion: can we group the 44 books of Cicero by category?  (#44)would like thoughts from @abrasax on this

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alpheios-project/alpheios_nemo_ui","title":"alpheios-project/alpheios_nemo_ui","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alpheios-project/alpheios_nemo_ui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@balmas in #44: would like thoughts from @abrasax on this "}],"action":{"name":"View Issue","url":"https://github.com/alpheios-project/alpheios_nemo_ui/issues/44#issuecomment-470920982"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alpheios-project/alpheios_nemo_ui/issues/44#issuecomment-470920982",
"url": "https://github.com/alpheios-project/alpheios_nemo_ui/issues/44#issuecomment-470920982",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by monzug** [comment]
ok. I will sort the books by category and provide a new list.

**Comment by monzug** [comment]
EPISTULAE: Letters to Atticus, letters to brutus, letters to his friends, Letters to his brother Quintus
PHILOSOPHIA: Academica, Brutus, De Inventione, De Optimo Genere Oratorum, De Fato, De Republica, De Senectute,  De Officiis,  De Amicitia, De Divinatione,  De Natura Deorum, De Finibus Bonorum et Malorum, Lucullus, Orator, On Oratory (De Oratore), Paradoxa Stoicorum, Partitiones Oratoriae, Timaeus, Topica, Tusculanae Disputationes
ORATORIA: Contra Rullum, De imperio Cn. Pompei, Cum Senatui gratias egit,  Cum populo gratias egit, For Marcus Caelius, In Caecilium, In Catilinam, In Verrem, Pro A. Caecina, Pro Archia, Pro C. Rabiro perduellionis reo, Pro Cluentio, Pro Fonteio, Pro L. Flacco, Pro Murena, Pro P. Quinctio, Pro S. Roscio Amerino, Pro Q. Roscio Comodeo, Pro Sulla, Pro Tullio

**Comment by balmas** [comment]
ok, grouping has been added. Still need design input on the display but the capability to group is there and the cicero texts updated to use it.

This was implemented by using the structured-metadata feature of the capitains guidlines (http://capitains.org/pages/guidelines#structured-metadata). I have added a dct:type metadata field to the __cts__.xml files for the categorized Cicero works and if that field is present and defined for a work, the collections display groups on it.  As currently implemented, it requires that all or none of the works for an author be organized into groups. It doesn't support some works for an author being grouped and some not.  

This change may require that we switch from using the source texts directly from the Perseus github repo and instead use our own fork. I will submit the metadata change in a pull request to Perseus but they may not wish to have this data change in their repo.

**Comment by monzug** [comment]
we are missing one book from Oratoria: Cum populo gratias egit

**Comment by monzug** [comment]
Actually, re- looking at all titles Cum populo gratias egit  is to the citizen after his return  / Post reditum ad quirites   in Alpheios.
the missing one is  Pro A. Caecina,

**Comment by monzug** [comment]
I add this comment here: why don't we have the title Cum populo gratias egit? it's in the xml but we are using a different title and not sure where is coming from. ideas?
