### ISSUE TITLE
additional greek texts

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#65]
Plato’s Apology, Euthyphro and Symposium; Lysias Oration (Funeral or Olypmic or both?); Longus Daphnis and Chloe;

**Comment by balmas** [comment]
I added these texts. @monzug when you have a chance, take a look and let me know if you find any major display problems with them.

**Comment by monzug** [comment]
1) Plato's Apology starts with 17a in perseus, not in Scaife and Alpheios: it starts with 1 then 17, then 17a
in the xml we have  <p><milestone n="1" unit="speech"/><milestone n="17" unit="page"/><milestone unit="section" resp="Stephanus" n="17a"/>
2) the fonts of the chapter's numbers are smaller than the font of the related sections, e.g. 23 is smaller than 23a     xml:
<div type="textpart" subtype="section" resp="perseus" n="23"><p><milestone unit="para" ed="P"/>ἐκ ταυτησὶ δὴ τῆς ἐξετάσεως, ὦ ἄνδρες Ἀθηναῖοι, <milestone n="23" unit="page"/><milestone unit="section" resp="Stephanus" n="23a"/>
3) Plato's Euthyphro: compare our version with Scaife and Perseus. we use the wrong tag in the dialog as in Scaife. <said who="#Εὐθύφρων"></said>  should be used in stead of   <label>ΕΥΘ.</label>  and 
<said who="#Σωκράτης">  instead of   <label>ΣΩ.</label>.  just as Perseus does.
if I double click on ΣΩ, there is nor result, on the contrary if lookup Σωκράτης  I get the following: dear little Socrates!
4) the text at 12b is not displayed correctly. it's a citation and the quotes and the name are not in the right place.
"
οὐκ ἐθέλει νεικεῖν· ἵνα γὰρ δέος ἔνθα καὶ αἰδώς.
" Stasinus Cypria Fr. 20ἐγὼ οὖν τούτῳ διαφέρομαι τῷ ποιητῇ. εἴπω σοι ὅπῃ;
5) also in the symposium, we use ΑΠΟΛ and in Perseus is  Ἀπολλόδωρος (= Appolodorus)  

the font issue (#2) is common on all 3 texts.

**Comment by monzug** [comment]
Both Funeral Oration by Lysias and Daphnis and Chloe by Longus are ok. back to you Bridget for Plato's issues.

**Comment by balmas** [comment]
ready for testing in beta environment

**Comment by balmas** [comment]
> 1. Plato's Apology starts with 17a in perseus, not in Scaife and Alpheios: it starts with 1 then 17, then 17a

I am hiding the speech and page numbers in the display, showing only section numbers now

**Comment by balmas** [comment]
>Plato's Euthyphro: compare our version with Scaife and Perseus. we use the wrong tag in the dialog as in Scaife.
>also in the symposium, we use ΑΠΟΛ and in Perseus is Ἀπολλόδωρος (= Appolodorus)

This was a deliberate markup choice by the PerseusDL in the latest version of the XML. It corresponds with the original Loeb edition display (and is how Loeb displays it). However @abrasax concurs that it is better to display the full speaker name so I have added it and hidden the abbreviated names.

**Comment by balmas** [comment]
>the text at 12b is not displayed correctly. it's a citation and the quotes and the name are not in the right place.

This should be fixed now.

**Comment by monzug** [comment]
Thanks! looks beautiful. tested on desktop and mobile.
